### PR TITLE
Compilation fixes

### PR DESCRIPTION
**Pull request by MarcelHB**
Hi, found some time again :)

Wanted to check out your progress and caught some things not working on Clang/in general. Mostly related to pointers that turned into smart pointers, minor standard compliance.

### CODE REVIEW

**Comment by bradallred** [comment]
I'm just going to revert fdfff69

Aside from these compile issues, we don't want to accidentally expose the raw pointer to anything. Better to require and explicit `get()` and leave the implicit conversion for comparisons only.

Are there really no `uint_xx_t` types available in C++03?

**Comment by MarcelHB** [comment]
Without `get()`, your code doesn't work for me (saying `comparing non-pointer type to NULL`), that's why. And inclusion of `cstdint` refuses to be compiled without an explicit Cxx11 flag.

Maybe `Holder` offers something else for equivalent checks, but without deeper inspection, I had a little doubt of its soundness.

**Comment by bradallred** [comment]
That's my point :)

If I revert that code will work again for you without using `get()` as it did before I made that commit. No idea why my clang doesn't complain (C++11?) and yours does, but there are other reasons to revert that anyway.

**Comment by MarcelHB** [comment]
Ok, then let's try this first.

**Comment by bradallred** [comment]
I've reverted that now. We should get 2da8004 in still. Care to send a new pull request with just that?

**Pull request closed without merging**
