### PR TITLE
Fixes for Windows, GCC7, videos

### PR DESCRIPTION
**Pull request by MarcelHB**
I wanted to try out your branch on my Windows 7/Linux and GCC7. Did not fully work, so I did some things:

* From `master`, I cherry-picked some specific fixes for Windows.
* I dealt with pickyness of "fall through"-accepted comments that do not cause warnings. :grin: 
* You introduced some things that collide with WinAPI macros (`CreateWindow`, `GetObject`).
* SDL videos are colorfully broken, playback even crashes on Windows (#115 I guess?)
* Some other things, one even was my bad.

Somewhere, whitespace slicing slipped in, sorry for that.

I cannot enter an IWD2 game right now, btw. But the changes look fresh enough for me to leave it to you. I just got:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
GemRB::View::SetFlags (this=this@entry=0xbaadf00dbaadf00d, arg_flags=arg_flags@entry=4,
    opcode=opcode@entry=2) at gemrb_subviews/gemrb/core/GUI/View.cpp:531
531             unsigned int oldflags = flags;
(gdb) bt
#0  GemRB::View::SetFlags (this=this@entry=0xbaadf00dbaadf00d, arg_flags=arg_flags@entry=4,
    opcode=opcode@entry=2) at gemrb_subviews/gemrb/core/GUI/View.cpp:531
#1  0x0000000069f1fc5a in GemRB::WindowManager::DestroyAllWindows (this=0x8adae0)
    at gemrb_subviews/gemrb/core/GUI/WindowManager.cpp:275
#2  0x0000000069ea4b59 in GemRB::Interface::HandleFlags (this=this@entry=0x8a41a0)
    at gemrb_subviews/gemrb/core/Interface.cpp:582
#3  0x0000000069ea7328 in GemRB::Interface::Main (this=0x8a41a0)
    at gemrb_subviews/gemrb/core/Interface.cpp:956
#4  0x000000000040d993 in main (argc=1, argv=0x2f2800)
    at gemrb_subviews/gemrb/GemRB.cpp:99
```
`DestroyAllWindows` iterates over freed or invalid instances, so `this->flags` is bad here. JFYI.

### CODE REVIEW

**Comment by bradallred** [comment]
IWD2 is the last on the list to do. BG 1&2 or IWD1 should work reasonably well; tho apparently 16fe6ed is bad even tho I cant reproduce the crash. Im sure ASAN will barf if I try it. You can safely revert it, it was for a PST problem anyway.

I'll have to examine this pull tomorrow.

**Comment by lynxlynxlynx** [comment]
Mostly looks fine. For the non-typoed fallthroughs, we have a define in cmake to make gcc checking laxer. Could've saved some effort there.

**Comment by bradallred** [comment]
I tried running with ASAN to pin down the crash issue, but that reported no issues. I suspect I have introduced undefined behavior somewhere.

you provided a stack trace which is helpful, but can you check if it was either 16fe6ed or 3e03585 that introduced it? I'm assuming this happens with BG2... I have no IWD2 saves to try and load. Starting a new game produces no issues for me.

**Comment by bradallred** [comment]
The pull looks fine. I'm confused about how replacing `GEM_EXPORT` with `GEM_EXPORT_T` which is `#defined` back to `GEM_EXPORT` makes a difference, but I'll trust you!

**Comment by bradallred** [comment]
the last commit will hopefully fix that crash

**Comment by MarcelHB** [comment]
Difference is solely on Windows where the compiler complains on `dllimport` (*) things that are actually defined in a template. Thus `GEMRB_EXPORT_T` that avoids this on Windows while preserving the definition on Mac/Linux.

(*) This definition somehow gets into `GemRB.cpp` that is _not_ supposed to be a shared library.

**Pull request merged**
